spring:
  flyway:
    enabled: false
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//10.86.3.140:1521/CLIE_PDB_QA.subnetprivatedb.vcncf.oraclevcn.com}
    username: ${DB_USERNAME:TCI_OWNER}
    password: ${DB_PASSWORD:TCI_Owner_2026!}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: ItDashboardHikariPool
  jpa:
    show-sql: false

app:
  errors:
    expose-details: true
  test:
    admin-email: ${TEST_ADMIN_EMAIL:}
    admin-password: ${TEST_ADMIN_PASSWORD:}

logging:
  level:
    com.coltefinanciera.itdashboard: INFO
    com.coltefinanciera.itdashboard.identity: DEBUG
    com.coltefinanciera.itdashboard.shared.exception: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: WARN