CREATE USER APP_CURSOR IDENTIFIED BY AppCursor123;

GRANT CONNECT TO APP_CURSOR;
GRANT RESOURCE TO APP_CURSOR;
GRANT CREATE SESSION TO APP_CURSOR;
GRANT CREATE TABLE TO APP_CURSOR;
GRANT CREATE VIEW TO APP_CURSOR;
GRANT CREATE SEQUENCE TO APP_CURSOR;
GRANT CREATE PROCEDURE TO APP_CURSOR;
GRANT CREATE TRIGGER TO APP_CURSOR;
GRANT CREATE TYPE TO APP_CURSOR;
GRANT UNLIMITED TABLESPACE TO APP_CURSOR;